<#import "layouts/base.ftlh" as base>
<@base.main title="Map">
    <div style="position:relative;overflow:hidden;"><a href="https://yandex.ru/maps/43/kazan/?utm_medium=mapframe&utm_source=maps" style="color:#eee;font-size:12px;position:absolute;top:0px;">Казань</a><a href="https://yandex.ru/maps/geo/kazan/53166501/?from=tabbar&ll=49.099977%2C55.767304&source=serp_navig&utm_medium=mapframe&utm_source=maps&z=10" style="color:#eee;font-size:12px;position:absolute;top:14px;">Казань</a><iframe src="https://yandex.ru/map-widget/v1/-/CCUUFOUThD" width="560" height="400" frameborder="1" allowfullscreen="true" style="position:relative;"></iframe></div>
</@base.main>

